### ISSUE TITLE
Optimise L2 uncertainties by saving Py6s output from L1B

### ISSUE THREAD

**Issue by ARamsay17** [nasa/HyperCP#140]
L2 uncertainties require the use of the py6s package to calculate direct ratios and solar zenith. We may optimise this process by saving this output from L1B, filtering bad timestamps in L1BQC and reading the data for use in the L2 uncertainty code.

**Comment by AlexisDeru** [comment]
solar zenith angle is now in the PY6S_MODEL group, but only for the first timestamp of each cast.

**Comment by oceancolorcoder** [comment]
Some bad timestamp filtering was commented out. Need to resolve before closing issue.

**Comment by oceancolorcoder** [comment]
Resolved with a851e775048f8b7d6c9ff40d651873ecf59058e2. Closing.
