### ISSUE TITLE
  ES, LI and LT should be used to calculate band convolved Rrs and LW

### ISSUE THREAD

**Issue by ARamsay17** [nasa/HyperCP#142]
The FRM-Class based L2 uncertainties are not correctly convolved. 

In the FRM-Class based, and HyperOCR default branch, Rrs and LW uncertainties are calculated directly from all input uncertainties: instrument noise, rho uncertainty and errors read from class based characterisation files. We need to find a good solution to apply convolved ES, LI, LT for use in calculating LW and Rrs for a given sensor.

**Comment by oceancolorcoder** [comment]
Resolved with PR #153
