### ISSUE TITLE
Single ancillary timestamp kept in `ProcessL1aqc.py`

### ISSUE THREAD

**Issue by raphidoc** [nasa/HyperCP#168]
Test with Algae-WISE data (manually operated ~ 3 min cast) showed the following behavior of  `bisect_left`:

https://github.com/nasa/HyperCP/blob/e0236090013f9e594c6b91bdda00f1b1088aba28/Source/ProcessL1aqc.py#L217-L223

`bisect_left` seems to select data after the max `esDateTime` if there is no ancillary timestamp between the min and max esDateTime. In that case, the lower and upper limits are set at the same index, and only a single value of ancillary data is kept, which is not enough for interpolation downstream.

This is more likely to happen with short casts, but it also strongly depends on how ancillary data is collected and the SeaBASS file is created. 
As it is not directly a problem with the code, this point may be more relevant in discussion?

**Comment by oceancolorcoder** [comment]
@raphidoc, after the course we will explore this issue. It is fine here for now rather than discussions.

**Comment by AlexisDeru** [comment]
I have tested a very simple solution which is to ensure the selection of an additional ancillary point. So far I do not see negative impact as everything is interpolated to the right timestamps later

**Comment by oceancolorcoder** [comment]
Resolved with PR 7f2bf11594194ebd6c1abf5db896c457d362f503. Closing.

**Comment by oceancolorcoder** [comment]
Updated this include 1 ancillary record before and 1 record after the radiometry.
