### ISSUE TITLE
Add IOP-based BRDF correction option

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#17]

**Comment by oceancolorcoder** [comment]
Implementation of updated Lee et al 2015 approach to be applied pending investigation by D'Alimonte et al

**Comment by juanchossn** [comment]
Tamito Kamiyama (Aequora, BRDF4OLCI team) looking into it.

**Comment by juanchossn** [comment]
Davide's team delivered Python scripts to perform L11 - must acknowledge them.
@AlexisDeru  embedded L11 in the code (see merged PR #159).

**Comment by oceancolorcoder** [comment]
Resolved with PR #159
