### ISSUE TITLE
TriOS; Factory files (Cal, Back) have NANs for many pixels

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#170]
In .dat files from Tartu, these have already been replaced, but for users without .dat files from Tartu, this is going to be an issue read/writing L0/L1A.

May need to replace all +NAN or -NAN in factory files with 0.0

**Comment by AlexisDeru** [comment]
NaN in calibration file are now convert to 0during the ingestion of factory cal

**Comment by oceancolorcoder** [comment]
Resolved with d973012902d8b4e94b01040286f89589c5745a87
