### ISSUE TITLE
SEABASS output file BRDF correction

### ISSUE THREAD

**Issue by Pipatthra** [nasa/HyperCP#174]
There is  an issue with SEABASS output file, BRDF correction is not stated in the rrs.

**Comment by oceancolorcoder** [comment]
Resolved in the dev branch with commits of May 21-22 (87572ae2943fc9e4c91256d108292a950f44966a, 8af907c548ea6d5e9c30ff4fc15b860fc342744f, 53360a534ddba7daef5af6dc659742314d280841).

Not yet promoted to master branch. If there is an urgent need for the fix now, please use dev or let us know and we can promote to master.
