### ISSUE TITLE
BRDF (M02 & L11) not being properly applied (top priority)

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#187]
"...BRDF correction are all artificially set to 1, meaning that the correction is doing nothing, for both Morel and Lee. I think this is link to the harmonization/iteration change, and that it is link to an error in the var assignment line 73 in ocbrdf/main.py
 
ds['C_brdf'].where(~ds['convergeFlag'])[:] = forward_mod0.where(~ds['convergeFlag'])[:] / forward_mod.where(~ds['convergeFlag'])[:]
 
while the right part of the equation is actually computing coefficients value around 0.9, the left part does not update the values in ds['C_brdf']."

**Comment by oceancolorcoder** [comment]
Resolved with 45a0ffa12d680be0aeed5dddb520737cda25ccc4

**Comment by oceancolorcoder** [comment]
Re-opened to trace unchanging L2 after BRDF

**Comment by AlexisDeru** [comment]
solve with commit dd2ce843c30871dcd19d15909d2483ba203e0f8f
