### ISSUE TITLE
Trios exemple L2 issue when writing seabass 

### ISSUE THREAD

**Issue by AlexisDeru** [nasa/HyperCP#189]
keyword station is not existing in the trios ancillary file
this cause an error in line 94 of SeaBassWritter.py

        if headerBlock['station'] == '' and ConfigFile.settings['bL2Stations'] == 1:
            station = node.getGroup('ANCILLARY').getDataset('STATION').data[0][2]

**Comment by oceancolorcoder** [comment]
Again? Why does this keep creeping back in? I'll look into it.

**Comment by oceancolorcoder** [comment]
Mine runs okay. Please check that your .hdr file was not corrupted. The version on the remote looks okay (i.e., contains the "station" key): https://github.com/nasa/HyperCP/blob/master/Config/sample_TRIOS_NOTRACKER.hdr

**Comment by AlexisDeru** [comment]
yes my bad, this is solved, I thought it was the "station" in Ancillary, but this is just the seabass haeder. the one on the repository work
