### ISSUE TITLE
Multi-threading scripted calls hang on punpy for Z17

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#223]
Running scripts like run_Sample_Data.py works fine when not multitasking, but the 4 threads jam up at the MC calls to Z17 and the code hangs. Cause remains unclear.

**Comment by raphidoc** [comment]
I found a problem here:

https://github.com/nasa/HyperCP/blob/079fe9c0551a2ddcc7a8610b1ccea981cf5b81e6/Source/Controller.py#L522-L523

When multithreading, it happens that line 522 returns true for multiple threads simultaneously. But one thread will execute line 523 before the others. In that case the following error will be thrown:

`FileExistsError: [Errno 17] File exists: '/D/Data/TEST/hypercp/multithreading/KORUS/L1A'`

All the falling threads (the ones attempting to create the already existing `pathOutLevel` folder) will wait for the other(s) thread to finish executing before returning the error.

However, that is probably not the cause of the issue. If `pathOutLevel`  already exists (e.g., you've tried to process and re-process with ` CLOBBER = True`), you won't run into this problem anymore.

I can process the KORUS data you provided with four threads in ~ 15 minutes. The code doesn't hang, but Z17 takes ~ 30 seconds. 
At some point before the end, only a single core still runs, but that could be normal as the four threads do not run synchronously, but each manages the 13 raw files independently.

I've sent the Z17 mat loading timing to a file to see if the concurrent threads are creating conflicts, but that doesn't seem to be the case. In fact, two threads have even accessed it and read it almost simultaneously (less than a second difference in access to the .mat file and ~ 15 seconds to execute the `load()` function).

You could try sending timing information to debug files from different places in the code to try understand how much time the different threads take to execute. I'll do it this way:    
```
import time
start = time.time()
start_perf = time.perf_counter()

>>>
Code to profile
>>>

write = f'Loading constants at {start} in {time.perf_counter() - start_perf:0.4f} seconds'
logger.debug(write)
# write to file in home each time the LUT is loaded
with open(os.path.join(os.path.expanduser('~'), 'zhang17.log'), 'a') as f:
    f.write(write + '\n')
```

**Comment by oceancolorcoder** [comment]
Your four threads did not hang? Interesting. Also interesting that it only takes 15s. Are you running for Z17 rho? (i.e., with the 10 MC runs for uncertainty)?

**Comment by raphidoc** [comment]
The run was made with Zhang 17 rho correction. The four threads do not hang on my machine. Loading the LUT takes ~15 seconds, and the calls to `ZhangRho.get_sky_sun_rho` take between ~15 to 40 seconds.

The `Propagate.Zhang_Rho_Uncertainty` (10 MC draw on 1 core) takes ~ 460 seconds to run.

So processing a 4.1 MB raw file (1614106.raw), which results in 4 spectra at L2, takes ~ 39 minutes (2359 seconds).

**Comment by oceancolorcoder** [comment]
Those timings make sense. I haven't timed LUT loading, but running ZhangRho usually takes me about 3 - 14s and Rho Uncertainty ~150s, without running multithreading, with another 10s to update instrument uncertainties in the slice. I'm on a Mac M3 Max 16 core with 64 GB RAM. On this machine, I have never gotten past Rho Uncertainty while multithreading, but I will keep trying. Just to confirm, when you were multithreading and logging the LUT load times, it would only load the LUT once, right? I.e., the global database variable in ZhangRho is working at L438?

**Comment by raphidoc** [comment]
Each tread loads the LUT only once, so for four threads, the LUT is loaded four times. 
The Zang 17 rho uncertainties are computed for each spectrum in L2 (25 five times ~300s in that case).

I tried using punpy propagate with more cores, but it failed with a numpy array not hashable error. 
Also note in punpy multiple cores, the LUT gets loaded once for each punpy threads.

**Comment by oceancolorcoder** [comment]
Not sure which commit to site, but issues now appear to be resolved on Mac and Linux.
