### ISSUE TITLE
PIU and visualizer updates bugs

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#241]
@ARamsay17 

Tried running with @ARamsay17's Friday PR on sample_pySAS sensor-specific, M99MA:

1st error was in PIU near L1743-1745:
```
File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 1743, in read_py6s_model
    if 'timetag' in res_py6s['wavelengths'][0]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'numpy.float64' is not iterable

```
I commented this clause out. (Should not be needed after the pop lines above it for timetag2, etc.)

Next error I get is a mismatch of array sizes for res_py6s datasets during PIU cosine correction:

```
File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 2214, in FRM
    direct_ratio, _ = self.interp_common_wvls(np.array(direct_ratio, float), res_py6s['wavelengths'], radcal_wvl)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 1440, in interp_common_wvls
    new_y = np.interp(newWavebands, x, y)  #InterpolatedUnivariateSpline(x, y, k=3)(newWavebands)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in interp
  File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/numpy/lib/function_base.py", line 1594, in interp
    return interp_func(x, xp, fp, left, right)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: fp and xp are not of the same length.
```

**Comment by ARamsay17** [comment]
The line 1743 "if 'timetag' in res_py6s['wavelengths'][0]:"

should read  "if 'timetag' in res_py6s['wavelengths']:"

Seems it is an error with the commit. I can issue another PR but maybe it's quicker for you to correct the line on your end. 

Although this was only necessary because I encountered situations in testing where res_py6s['wavelengths'] included the string 'Timetag' which I thought should be impossible.

**Comment by oceancolorcoder** [comment]
@ARamsay17 yes, that first error is resolved. The second error listed above is still a problem.
