### ISSUE TITLE
Error in L1BQC for TriOS_NOTRACKER sample

### ISSUE THREAD

**Issue by ARamsay17** [nasa/HyperCP#243]
A warning occurs when running TriOS_NOTRACKER from raw in the Class-Based or Factory regime. I cannot run either file past L1BQC. 

Console output:
 
Process Single Level: /home/ar17/PycharmProjects/FRM4SOC/HCP/Data/Sample_Data/Manual_TriOS/Class-Based/L1BQC/FRM4SOC2_FICE22_UT_20220719_082000_L1BQC.hdf - SUCCESSFUL
Process Single Level
ProcessL2: /home/ar17/PycharmProjects/FRM4SOC/HCP/Data/Sample_Data/Manual_TriOS/Class-Based/L1BQC/FRM4SOC2_FICE22_UT_20220719_082000_L1BQC.hdf
6S model not found, probably because lower level data was processed before v1.2.5. 
processFilesMultiLevel - DONE
Time elapsed: 0 Minutes

**Comment by oceancolorcoder** [comment]
Resolved with 1f2cea5ed4fcbcf860cc24a0df92f49f4b13b60d
