### ISSUE TITLE
FRM Branch Uncertainty Budget

### ISSUE THREAD

**Issue by ARamsay17** [nasa/HyperCP#25]
Updates are required to apply proper uncertainty analysis and propagation for FRM branch processing, so that the uncertainties correspond to corrected outputs.

**Comment by juanchossn** [comment]
@ARamsay17 , this issue description is a bit vague, could you give more detail in the description? Otherwise, if already solved, propose it for closure

**Comment by oceancolorcoder** [comment]
Closing this issue in light of more specific issues that followed.
