### ISSUE TITLE
TypeError: ufunc 'radians' not supported for the input types

### ISSUE THREAD

**Issue by kristalikas** [nasa/HyperCP#252]
![Screenshot 2024-10-14 at 13 24 12](https://github.com/user-attachments/assets/2aa78a54-4a77-40f4-8bd6-e03dce67e85a)

![image](https://github.com/user-attachments/assets/294f9d7f-e2da-4bec-88c2-762bfa8de8ea)

**Comment by oceancolorcoder** [comment]
Hi @kristalikas, 

What dataset were you processing here? If the sample TriOS, did you confirm the ancillary was set to the proper file in the Main window?

**Comment by kristalikas** [comment]
@oceancolorcoder 
I was processing Alkor dataset with one single ancillary file for the whole cruise. While majority of the stations went through the processing, this error message repeatedly appeared on others.

**Comment by oceancolorcoder** [comment]
The problem appears to be with interpretation of the latitude provided in the ancillary file. Try double checking that ancillary file (even just fcheck-ing the file might be enough) that the lat/lon values are all valid.

**Comment by oceancolorcoder** [comment]
@kristalikas are you still encountering this error?

**Comment by kristalikas** [comment]
Thanks! Indeed, fcheck-ing revealed that all lat/lon values were not valid, which caused this issue.

**Comment by oceancolorcoder** [comment]
@kristalikas glad to hear it. Closing issue.
