### ISSUE TITLE
Issue with Uncertainty Breakdown Plots

### ISSUE THREAD

**Issue by kristalikas** [nasa/HyperCP#254]
![Screenshot 2024-10-14 at 14 47 09](https://github.com/user-attachments/assets/c6fffcbe-806d-4a40-a6ff-fa1234420348)

![Screenshot 2024-10-14 at 14 47 53](https://github.com/user-attachments/assets/4e640f20-acfe-4ea0-b7ca-072b5f4ea8b1)

**Comment by oceancolorcoder** [comment]
@kristalikas, thanks for posting. This is an odd one. We will look into it and try to reproduce. Please email me the L1BQC file and note the issue # in the subject. Thanks.

**Comment by kristalikas** [comment]
@oceancolorcoder Thanks! I sent the file.

**Comment by oceancolorcoder** [comment]
@kristalikas thanks for sending the files. We are looking at it and will get back asap.

**Comment by ARamsay17** [comment]
@kristalikas Thank you for the files. I believe this has been solved on my side but I will be sure to test using the data you provided before finalising the changes.

**Comment by oceancolorcoder** [comment]
This should be solved with PR #263 available shortly on master branch. Closing (but do not hesitate to reopen if you continue to experience this error).
