### ISSUE TITLE
TriOS Sample Data Wrong

### ISSUE THREAD

**Issue by ShenZhongxia** [nasa/HyperCP#266]
### When I run the TriOS Sample Data，there is something wrong
when I choice Raw(BIN)---L2(HDF5),there is no output of L1AQC,
and report "UnboundLocalError: cannot access local variable 'esDateTime' where it is not associated with a value"
![屏幕截图 2024-10-28 162425](https://github.com/user-attachments/assets/3d24387a-c8ae-4f1d-a2e4-2fb8c1db5208)
this is my choice:
Configuration File: sample_TRIOS_NOTRACKER.cfg
Ancillary File (SeaBASS format):Manual_TriOS/ FICE22_TriOS_Ancillary.sb
Raw files:SAM_8166_RAW_SPECTRUM_FRM4SOC2_FICE22_UT_20220719_080000.mlb
![屏幕截图 2024-10-28 162451](https://github.com/user-attachments/assets/5d434a37-1408-4a58-83c9-dbcb41cbeb33)

**Comment by ARamsay17** [comment]
@ShenZhongxia from your error report you seem to only be selecting one raw data file, is that correct? TriOS data is organised differently to Seabird where each radiometer has an associated '.mlb' file. The HyperCP currently requires all three to be selected per cast.

Raw files:
SAM_8166_RAW_SPECTRUM_FRM4SOC2_FICE22_UT_20220719_080000.mlb
SAM_8329_RAW_SPECTRUM_FRM4SOC2_FICE22_UT_20220719_080000.mlb
SAM_8595_RAW_SPECTRUM_FRM4SOC2_FICE22_UT_20220719_080000.mlb

Hope this helps.

**Comment by oceancolorcoder** [comment]
@ShenZhongxia did @ARamsay17's suggestion work for you? Please let us know and we will close the issue. Thanks
