### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by kristalikas** [nasa/HyperCP#267]
While processing TriOS RAMSES data in full FRM mode, I received this error: 
![image](https://github.com/user-attachments/assets/d47c710a-b951-4ab2-bcdd-508c80af5e21)

Processing configuration:
![image](https://github.com/user-attachments/assets/3c026e8a-c811-446a-bd1c-e6a60e3724f3)

**Comment by oceancolorcoder** [comment]
@kristalikas, apologies for the delay. Just back from vacation and digging out. 

To clarify, are you using HyperCP 1.2.8? Could you upload the relevant L1BQC file to the Box (you should have received an email invitation), along with supporting configuration/calibration files if they are not already provided?

**Comment by kristalikas** [comment]
Thanks! No worries! I have access to the Box, but I am not able to upload there files.
Yes, I am using v1.2.8.

**Comment by oceancolorcoder** [comment]
Apologies, you should be able to upload now.

**Comment by kristalikas** [comment]
Thanks! I uploaded the input files. The cal/char files are the same as for issue #253.

**Comment by oceancolorcoder** [comment]
Hi @kristalikas,
 
Issue resolved in nasa:dev with 8ebcdeabdee0ecb130fc06ae39da55303dd2de00
Closing.
