### ISSUE TITLE
MainConfig cmdline get overwritten with default in L1a processing

### ISSUE THREAD

**Issue by raphidoc** [nasa/HyperCP#287]
MainConfig created via cmdline gets overwritten with default in L1a processing.
The problem is here:
https://github.com/nasa/HyperCP/blob/7921730aa9d5afc7780ffded0646decf66eaa173/Source/ProcessL1a.py#L24

`.lower` should be `.lower()` to return the string, not the method.

**Comment by oceancolorcoder** [comment]
Nice catch. I knew there was something funny going on. I'll fix it once this batch is done. Thanks.
