### ISSUE TITLE
Dealing with non-UTF-8 encoding in RAW data file 

### ISSUE THREAD

**Issue by belasi01** [nasa/HyperCP#290]
Unfortunately, some of my HyperSAS data have a French accent (in my name, actually!!) in the header of the RAW file. Because of that, the current readSATHDR function fails to read my RAW file. 

I have been able to modify the function to read my raw data, but the code now fails to write the HDF L1A file later in the processing. I don't know how to fix that issue myself (as a python beginner). 

Thanks for your help

Simon B**é**langer

**Comment by raphidoc** [comment]
I added a fix for that in pull request #292  by try except and adding the `error = 'ignore'` argument to the decode method.
The result is that any non utf-8 encoded character gets stripped (raphaël becomes raphal).

**Comment by oceancolorcoder** [comment]
Thanks Raphaël. I will see to merging your PR in when I get back.

**Comment by juanchossn** [comment]
Solved in PR #292  , still to be tested.

**Comment by belasi01** [comment]
On my side I have tested the correction. The raw file are reading well but the code failed later...  need more testing.

**Comment by oceancolorcoder** [comment]
The fixed is now merged into the dev branch. Simon, you could test on that branch or wait until I merge up to master in coming weeks. Once you confirm it's working for you, we'll close the issue.
