### ISSUE TITLE
Automatically download FidRadDB characterization files

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#50]
Instrument characterization files stored in EUMETSAT OCDB can be automatically downloaded and stored locally as needed

**Comment by AlexisDeru** [comment]
I am checking with Gabriele for the module installation. I will come back to you

**Comment by oceancolorcoder** [comment]
Looks like your .gitignore may have been changed/lost. There were 113 new files associated with the PR, most associate with "tests" directories. It looks like you just pasted the whole fidraddb_api repo into Source. Not sure this is the best solution.

**Comment by oceancolorcoder** [comment]
This will be resolved once the FidRadDB code is included in a conda-forge library and added to environment.yml

**Comment by AlexisDeru** [comment]
Last PR solve this issue, a new package is needed. the environment.yml is up to date, and tested on my side (linux).
If you want to install the new package only in your current env, you can with the cmd:
conda install -c ocdb -c conda-forge ocdb-client

**Comment by oceancolorcoder** [comment]
Issue resolved with PR commit 84d4799a958196adc7abb01c7a887263bcfd143c
