### ISSUE TITLE
SeaBird Non-FRM Class-based

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#84]
ProcessL2.ensembleReflectances:

SeaBird in "Factory" mode should calculate class-based uncertainties using class-based RADCAL uncertainties for SeaBird.

@ARamsay17

**Comment by AlexisDeru** [comment]
Issue fix by PR #90 
The value obtained are still non-realistic, but we have the same issue on the CLASS-BASED uncertainty. The 2 process are really similar and the solution should solve both. I think Ashley is currently looking at the high values issue.

**Comment by oceancolorcoder** [comment]
Thanks Alexis. Holding issue open until unrealistic uncertainties resolved.

**Comment by AlexisDeru** [comment]
Issue is due to a bad interpolation of uncertainty parameters. It was corrected for Class-based but we forgot the factory interpolation. Everything is in order with the last PR.

**Comment by oceancolorcoder** [comment]
Closing issue with PR commit 8f31eb8c1431ba90ccc82f2b7a76bf8bd0d84196
